title: "<img src='https://github.com/FENGSim/fengsim.github.io/blob/9baae68ecae28a119244b6c4f67a00336b09b6aa/image/image1.svg' alt='FENGSim' height='50'>"
description: "High-Fidelity Numerical Simulation and Adaptive Processing"
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#ffffff"
  gradient_left: "#16222a"
  gradient_right: "#3a6073"
  section_title: "#000000"
  link: "#ff3100"
exclude:
  - toolkit
  - starter
  - framework
  - cli
  - docs